Updated apiservice
adaptdk/media_skyfish pull request #9
Opened 2018-01-16 16:05 UTC by EdgarasDamkus

2018-01-24 15:24 UTC, irmantasp requested changes

2018-01-24 15:24 UTC, irmantasp commented on media_skyfish.routing.yml
>  media_skyfish.media_skyfish_controller_hello:
shouln't this already be removed?

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
>   *
Class description would be nice.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +        // @TODO set timestamp for cache
Wow cowboy, hold your horses and remove todo comments :)

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +   *
missing param description

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +        // @TODO set timestamp for cache
Wow, todo: remove todos.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +    return $cache->data ?? [];
Return description for this method is wrong, at it returns array or empty array.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +  public function getImageMetadata($image) {
If you are using variable type declarations - please use them everywhere.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +      // @todo: if no image/download link - throw an error.
repeat previous todo: remove todos.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +  public function getImageTitle($img_id) {
Again, missing variable type declaration.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +  public function getFilename($img_id) {
Also here, and maybe in another places.

2018-01-24 15:24 UTC, irmantasp commented on src/ApiService.php
> +    $request = $this->doRequest('/media/' . $img_id . '/download_location');
What if authorization fails and there is no request data returned?

2018-01-24 15:24 UTC, irmantasp commented on src/ConfigService.php
> +   * Initialize function checks if user's or global data should be user.
What?

2018-01-24 15:24 UTC, irmantasp commented on src/ConfigService.php
> +   *   If not empty return key.
Sooo it returns key, but key is boolean value?

2018-01-24 15:24 UTC, irmantasp commented on src/ConfigService.php
> +   * @return array|mixed|null
How in da world it can be array, mixed or null? 
if it is cache time - its only integer, or null.

2018-01-24 15:24 UTC, irmantasp commented on src/Controller/MediaSkyfishController.php
> +      '#markup' => 'Test folders id: 946499 and 949137',
Why is this even here? If you want to write tests for something, please write them.

2018-01-24 15:24 UTC, irmantasp commented on src/Controller/MediaSkyfishController.php
>    public function hello() {
Remove this method and controller itself.

2018-01-24 15:24 UTC, irmantasp commented on src/Form/MediaSkyfishSettingsForm.php
> +      '#title' => $this->t('Cache time in minutes'),
Did you check with cache settings? Does it realy has to be in minutes or you do convert this value?

2018-01-24 15:24 UTC, irmantasp commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +
Too much of newlines

2018-01-24 15:24 UTC, irmantasp commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +      // @todo: throw an error;
todos.

2018-01-24 15:24 UTC, irmantasp commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
>  }
please add new line at the end of the file

2018-01-24 15:24 UTC, irmantasp commented on src/ConfigService.php
> +   *   If not empty return key.
so why is it boolean?

2018-01-24 15:24 UTC, irmantasp commented on src/ConfigService.php
> +   * @return array|mixed|null
how it can be this type of variable?

2018-01-24 15:24 UTC, irmantasp commented on src/Controller/MediaSkyfishController.php
>     * Hello.
Please remove this controller.

2018-01-24 15:24 UTC, irmantasp commented on src/Controller/MediaSkyfishController.php
> +      '#markup' => 'Test folders id: 946499 and 949137',
No hardcoding!

2018-01-24 15:24 UTC, irmantasp commented on src/Form/MediaSkyfishSettingsForm.php
> +   *   Array of configs.
What kind of configs?

2018-01-26 08:01 UTC, andriusPr requested changes

2018-01-26 08:01 UTC, andriusPr commented on js/jquery.simplePagination.js
> +/**
In general 3rd party libraries and content are forbidden, so do not commit any. Instead, document for your users how to find and install the library/content themselves.

Read more:
https://www.drupal.org/node/422996

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    parent::__construct($configuration, $plugin_id, $plugin_definition, $event_dispatcher, $entity_type_manager, $validation_manager, $module_handler, $token);
holly shit, 8 arguments :D

Just a comment.... Nothing to do here as I understand :D

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    }
If you don't have any folders, maybe it make sense to return form here? That code bellow seems to be useless in this case.

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +      }
If possible, please split into separate methods, doesn't look nice when there is three level nesting.

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +
Don't think this white space is needed

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +
Do you really want this white space?

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +   * @return array
you are returning "array $images".

2018-01-26 08:01 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    unset($form['upload']);
Please write a comment why do you need to unset.

2018-01-26 08:02 UTC, andriusPr commented
@EdgarasDamkus @irmantasp all files are missing:
https://www.drupal.org/docs/develop/coding-standards/api-documentation-and-comment-standards#file

2018-01-26 08:20 UTC, mindaugas-laurinaitis requested changes

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on js/jquery.simplePagination.js
> +/**
Would it be possible to have this from dns? instead of adding it to project

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +      return NULL;
I would recommend to be consistent on returns - to use NULL or FALSE, but not both

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +      case 400:
How about having an array with status code as key and value as message? this switch doesn't look good

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +        $message = 'You need to be logged in to access the resource';
I think messages should be translatable, if they will be shown to users

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +        $message = FALSE;
So if there was an unknown error, we do nothing? How about having some default message for unknown errors?

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +        \Drupal::cache()->set($cache_id, $folders, time() + $this->cache * 60);
What's that 60? Looks like some magic number. And use \DateTime object instead of time()

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +    $this->cache = $this->config->getCacheTime();
cache is not defined. please add that property

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +  public function getImagesInFolderWithoutCache(int $folder_id) {
consistency should be kept - typecast should be added on all functions/parameters

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +    if ($image->download_url === FALSE) {
Consistency should be kept - FALSE === $variable or $variable === FALSE should be used, but not both

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +    $filename = substr($full_filename, 0, (strrpos($full_filename, ".")));
Consistency should be kept on using single or double quotes

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/ApiService.php
> +    $request = $this->doRequest('/media/' . $img_id . '/download_location');
How about having a pattern in const and using sprintf?

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Form/MediaSkyfishUserSettingsForm.php
> +    $hmac = hash_hmac('sha1', $key . ':' . time(), $secret);
isn't it the same as getHmac function?

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Form/MediaSkyfishUserSettingsForm.php
> +  protected function getEditableConfigNames() {}
is that an empty function?

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Form/MediaSkyfishUserSettingsForm.php
> +    $client = \Drupal::httpClient();
Dependency injection should be used

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Form/MediaSkyfishUserSettingsForm.php
> +  public function validateLogins(string $key, string $secret, string $username, string $password) {
I don't think this function belongs here in a form. It's not a forms responsibility to validate logins. Also number of parameters should be decreased if possible

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    $this->logger = \Drupal::service('logger.channel.media_skyfish');
How about dependency injection here?

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +  public function __construct(array $configuration, $plugin_id, $plugin_definition, \Symfony\Component\EventDispatcher\EventDispatcherInterface $event_dispatcher, \Drupal\Core\Entity\EntityTypeManage
Import classes used.

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    unset($form['upload_location'], $form['extensions'], $form['multiple']);
A comment why it is unsetting would be nice to have

2018-01-26 08:20 UTC, mindaugas-laurinaitis commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +    $data = \Drupal::httpClient()->get($image->download_url)->getBody();
Dependency injection. And consider moving file saving to a service instead of having it in form

2018-01-26 08:29 UTC, mindaugas-laurinaitis commented
@EdgarasDamkus @irmantasp How about some automated tests?

2018-01-26 11:29 UTC, irmantasp commented on css/simplePagination.css
> +* CSS themes for simplePagination.js
External libraries could be downloaded with composer. do you agree @mindaugas-laurinaitis ?

2018-01-26 11:29 UTC, irmantasp commented on js/jquery.simplePagination.js
> + * simplePagination.js v1.6
javascript library also could be downloaded with composer.json, agreed @mindaugas-laurinaitis ?

2018-01-26 11:29 UTC, irmantasp commented on js/jquery.simplePagination.js
> +})(jQuery);
Also, please use include and use minified version instead of default one.

2018-01-26 11:29 UTC, irmantasp commented on js/media_skyfish.js
> +        var perPage = 10;
this should not be hardcoded. it should be value, that can be taken from the configuration.

2018-01-26 11:29 UTC, irmantasp commented on src/ApiService.php
> + * Service that connects to and get data from Skyfish.
Unclear description.

2018-01-26 11:29 UTC, irmantasp commented on src/ConfigService.php
> +    $this->key = empty($this->user->field_skyfish_api_user->value) ?
is this really empty?

2018-01-26 11:29 UTC, irmantasp commented on src/Form/MediaSkyfishSettingsForm.php
> +        ' max' => 999,
Ya kidding me, right? 999?! is it 999 and not 9999 ?  or 9999. if you are not sure, change this to select field, with predefined values, ranging from 0 - which is not cached, to 24 hours. if you want to.

2018-01-26 12:11 UTC, irmantasp commented on src/ApiService.php
> +        $message = 'You need to be logged in to access the resource';
They are not visible for users, these are logged to logger.

2018-01-26 12:12 UTC, irmantasp commented on src/ApiService.php
> +        $message = FALSE;
Since it depends on status codes, anything wrong returns 500, or 400.

2018-01-26 12:23 UTC, irmantasp commented on src/ApiService.php
> +    if ($image->download_url === FALSE) {
We keeep it as $variable === FALSE.

2018-01-26 15:18 UTC, irmantasp commented on src/ApiService.php
> +    $this->cache = $this->config->getCacheTime();
Solved.

2018-01-29 15:03 UTC, irmantasp commented
@andriusPr @files is not required on Class'es files. It is only requirement for module file, Classes for drupal 8 uses annotations now.

2018-01-29 17:02 UTC, irmantasp commented
@andriusPr @mindaugas-laurinaitis please review current PR state if possible to if there is anything else to improve after changes, besides what still has to be changed.

2018-01-30 06:49 UTC, mindaugas-laurinaitis commented on src/ConfigService.php
> +    return $cache->getTimestamp();
An empty line should be added before return

2018-01-30 06:53 UTC, mindaugas-laurinaitis commented
@irmantasp Looks good. Have your tried running phpmd?

2018-01-30 07:24 UTC, andriusPr commented on src/Plugin/EntityBrowser/Widget/SkyfishWidget.php
> +
I actually don't like those useless white spaces :)

2018-01-30 07:25 UTC, andriusPr commented on media_skyfish.libraries.yml
> +    /libraries/contrib/simplepagination/jquery.simplePagination.js: {}
will it work without this library?

2018-01-30 07:35 UTC, irmantasp commented on media_skyfish.libraries.yml
> +    /libraries/contrib/simplepagination/jquery.simplePagination.js: {}
Yes, it works without a library, as the library is just cosmetic

2018-01-30 07:37 UTC, irmantasp commented
@mindaugas-laurinaitis nope, not yet.

2018-01-30 08:15 UTC, andriusPr approved these changes

2018-01-30 10:36 UTC, irmantasp commented
@andriusPr @mindaugas-laurinaitis can you take a look at last commit, and either approve your reviews or add anything else? If this is approved, can we move it along and add to drupal.org repo?

2018-01-30 11:00 UTC, mindaugas-laurinaitis approved these changes
Looks good

2018-01-30 11:44 UTC, irmantasp approved these changes

2018-01-30 11:46 UTC, merged